logging:
  level:
    org:
      springframework: INFO
spring:
  # H2
  h2:
    console:
      enabled: true
  # Thymeleaf
  thymeleaf:
    template-loader-path: classpath:/templates
    suffix: .html
    cache: false
# GraphQL
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

# GraphiQL
graphiql:
  enabled: true
  endpoint: /graphql
  mapping: graphiql