INSERT INTO application (application_id, app_name, description, owner) VALUES (1, 'Football','Application for Fantasy Football', 'aaron.carlson');
INSERT INTO application (application_id, app_name, description, owner) VALUES (2, 'Baseball','Application for Fantasy Baseball', 'aaron.carlson');
INSERT INTO application (application_id, app_name, description, owner) VALUES (3, 'Basketball','Application for Fantasy Basketball', 'aaron.carlson');
INSERT INTO ticket (id, title, description, application_id, status) VALUES (1, 'Sort Feature','Add the ability to sort tickets by severity',1,'OPEN');
INSERT INTO ticket (id, title, description, application_id, status) VALUES (2, 'Search Feature','Add the ability to search by invoice date',2,'IN PROGRESS');
INSERT INTO ticket (id, title, description, application_id, status) VALUES (3, 'Audit','Add the ability to audit by year',3,'CLOSED');
INSERT INTO release (id, description, release_date) VALUES (1,'Q1 Release Containing High Priority Bugs', '2030-02-14');
INSERT INTO release (id, description, release_date) VALUES (2,'Q2 Release Containing High Priority Enhancements', '2030-05-27');
INSERT INTO release (id, description, release_date) VALUES (3,'Q3 Release Containing Bugs', '2030-09-14');
INSERT INTO release (id, description, release_date) VALUES (4,'Q4 Release Containing Enhancements', '2030-12-10');
INSERT INTO ticket_release (release_fk, ticket_fk) VALUES (1,3);
INSERT INTO ticket_release (release_fk, ticket_fk) VALUES (2,1);
INSERT INTO ticket_release (release_fk, ticket_fk) VALUES (2,2);